FROM node:24-alpine

WORKDIR /app

COPY package*.json /app/

RUN npm ci --only=production

COPY . . 

EXPOSE 5000

CMD ["node", "app.js"]

# FROM python:24-alpine

# WORKDIR frontend/

# COPY requirements.txt /frontend

# RUN pip install requirements

# COPY . . 

# CMD ["pip", "app.py"]



