FROM node:alpine3.22 AS builder

WORKDIR /frontend

COPY package*.json ./

RUN npm ci 

COPY . .

RUN npm run build 

FROM nginx:1-alpine AS runtime

RUN rm -rf /usr/share/nginx/html/*

COPY --from=builder /frontend/build /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]




