services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  backend:
    image: ${DOCKER_USERNAME}/backend:latest
    restart: unless-stopped
    ports:
      - '8080:5000'
    environment:
      - MONGODB_URL=mongodb://mongo:27017/mern_db
      - PORT=5000
      - NODE_ENV=production
    depends_on:
      - mongo

  frontend:
    image: ${DOCKER_USERNAME}/frontend:latest
    restart: unless-stopped
    ports:
      - '80:80'
    depends_on:
      - backend

volumes:
  mongo-data:
